language: python
python:
- '3.6'
install:
- pip install -r requirements.txt
addons:
  sonarcloud:
    organization: "pereBlaiseTokenSonar"
    token:
        secure: "N/62X8jdqinVdTH+EBxB049R3WYvpUqeqM5bzoUu+5vnqsSJGl8EiLhWo73h+O4pVj7O6hgxGW5mn1xG7NOg6negrWR/ML2NMeebvBhh7T5dG0uhmGA2riIBZBtsdYxxP9bO2e8mcAXytqg1IiMcjvmlSbev7gmcm/ymXXvKWQxuNU2mRAXf0rE5fylLkSgEUI/JlI7rDWb/ANadq0GS5Mdgw5WPLzKCpQYJWSZnm6x+q+WMZaGoFd4cA6uppD9r2Va6XkMDN17DtE2DExWNtXvDcU4xNoK7sU6rZzcECiHUlE7QHM+oTJcrViuuT8vEASPIRr70MTsdeJK3fQ2hFNIch+xP1VTfwYqVXKE9kkxPHywj8BVRLeAyMvAPzAEbgzVeNIZSPg+/uPZsGPk7ZcRyy1m72HcuIhwYdnR7StstxsBE0NiBm+q8Z+NksySNAWjqX/np5nnsCUn0ap6dfiMBsMZx1ppXZzdr5YY/ZJGk9KYZ4OYZDCn7J+/iN6Mn4qDsGduZqgcL1ZO0lo7xflCOe/BzzlBP06jTquTRtOTwa59h2+uYY1dkt+JYBPGv/1E0LcTZdDJ1k01aa4cb8c9CEJRNxdG2J72rz5mURGWnrNcQrUx8a90xMyJJkLxKR7blVkqCyiM1nAWM5W+hQRmnNg0anQqJfqnsVeQfVLU="
script:
- pytest
- sonar-scanner
