language: python
python:
  - "3.6"
# command to install dependencies
install:
  - pip install -r requirements.txt
addons:
  sonarcloud:
    organization: "pereBlaiseTokenSonar" # the key of the org you chose at step #3
# command to run tests
script:
  - pytest # or py.test for Python versions 3.5 and below
  - sonar-scanner
